modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="loltomes"
version="${file.jarVersion}"
displayName="LoL Tomes"
logoFile="loltomes.png"
authors="Arun Persad"
description='''
A collection of Minecraft enchantments based on League of Legends champions.
'''

[[dependencies.loltomes]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.loltomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
